name: "Github Action Readme Learn Section"
description: "Populates the learning section in your github readme with data from notion"
author: devorein

inputs:
  database_id:
    description: "The id of the database"
    required: true

branding:
  icon: "box"
  color: "gray-dark"

runs:
  using: "node12"
  main: "dist/index.js"
